import { IAuth } from "../store/interfaces/auth.interface";
import { IEmpleados } from "../store/interfaces/employee.interface";

export const user: IAuth = {
  data: {
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.sampleToken1234567890",
    user: {
      id: 1,
      nombre: "Demo User",
      correo: "demouser@company.com",
      cargo: "admin",
      departamento: "Tecnología",
      oficina: "México",
      estadoCuenta: "Activo",
    },
  },
  status: "success",
};

export const employees: IEmpleados = {
  status: "success",
  data: [
    {
      id: 1,
      nombre: "Carlos Pérez",
      correo: "carlos.perez@example.com",
      cargo: "Desarrollador Frontend",
      departamento: "Tecnología",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 2,
      nombre: "Ana Martínez",
      correo: "ana.martinez@example.com",
      cargo: "Analista de Datos",
      departamento: "Inteligencia de Negocios",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
    {
      id: 3,
      nombre: "Luis Gómez",
      correo: "luis.gomez@example.com",
      cargo: "Diseñador UX/UI",
      departamento: "Diseño",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 4,
      nombre: "Marta López",
      correo: "marta.lopez@example.com",
      cargo: "Gerente de Proyecto",
      departamento: "Operaciones",
      oficina: "Argentina",
      estadoCuenta: "Activo",
    },
    {
      id: 5,
      nombre: "Javier Fernández",
      correo: "javier.fernandez@example.com",
      cargo: "Administrador de Sistemas",
      departamento: "Infraestructura",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 6,
      nombre: "Sofía Ramírez",
      correo: "sofia.ramirez@example.com",
      cargo: "Especialista en Marketing",
      departamento: "Marketing",
      oficina: "Perú",
      estadoCuenta: "Activo",
    },
    {
      id: 7,
      nombre: "Diego Torres",
      correo: "diego.torres@example.com",
      cargo: "Científico de Datos",
      departamento: "Inteligencia de Negocios",
      oficina: "Uruguay",
      estadoCuenta: "Activo",
    },
    {
      id: 8,
      nombre: "Elena Vega",
      correo: "elena.vega@example.com",
      cargo: "Consultor Técnico",
      departamento: "Tecnología",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 9,
      nombre: "Mario Sánchez",
      correo: "mario.sanchez@example.com",
      cargo: "Gerente Comercial",
      departamento: "Ventas",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 10,
      nombre: "Laura Ortiz",
      correo: "laura.ortiz@example.com",
      cargo: "Asistente Administrativo",
      departamento: "Administración",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 11,
      nombre: "Andrés Ruiz",
      correo: "andres.ruiz@example.com",
      cargo: "Especialista en Redes",
      departamento: "Infraestructura",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
    {
      id: 12,
      nombre: "Valeria Castillo",
      correo: "valeria.castillo@example.com",
      cargo: "Analista Financiero",
      departamento: "Finanzas",
      oficina: "Perú",
      estadoCuenta: "Activo",
    },
    {
      id: 13,
      nombre: "Fernando Gil",
      correo: "fernando.gil@example.com",
      cargo: "Desarrollador Backend",
      departamento: "Tecnología",
      oficina: "Uruguay",
      estadoCuenta: "Activo",
    },
    {
      id: 14,
      nombre: "Patricia Díaz",
      correo: "patricia.diaz@example.com",
      cargo: "Especialista en SEO",
      departamento: "Marketing",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 15,
      nombre: "Hugo Vargas",
      correo: "hugo.vargas@example.com",
      cargo: "Ingeniero de Software",
      departamento: "Tecnología",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
    {
      id: 16,
      nombre: "Gabriela Flores",
      correo: "gabriela.flores@example.com",
      cargo: "Gerente de Recursos Humanos",
      departamento: "Recursos Humanos",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 17,
      nombre: "Ricardo Castro",
      correo: "ricardo.castro@example.com",
      cargo: "Desarrollador Fullstack",
      departamento: "Tecnología",
      oficina: "Argentina",
      estadoCuenta: "Activo",
    },
    {
      id: 18,
      nombre: "Claudia Mendoza",
      correo: "claudia.mendoza@example.com",
      cargo: "Analista de Soporte",
      departamento: "Infraestructura",
      oficina: "Perú",
      estadoCuenta: "Activo",
    },
    {
      id: 19,
      nombre: "Tomás Herrera",
      correo: "tomas.herrera@example.com",
      cargo: "Administrador de Base de Datos",
      departamento: "Tecnología",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 20,
      nombre: "Silvia Romero",
      correo: "silvia.romero@example.com",
      cargo: "Diseñadora Gráfica",
      departamento: "Diseño",
      oficina: "Uruguay",
      estadoCuenta: "Activo",
    },
    {
      id: 21,
      nombre: "Isabel Peña",
      correo: "isabel.pena@example.com",
      cargo: "Asistente de Ventas",
      departamento: "Ventas",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 22,
      nombre: "Oscar León",
      correo: "oscar.leon@example.com",
      cargo: "Analista de Negocios",
      departamento: "Operaciones",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
    {
      id: 23,
      nombre: "Lucía Vargas",
      correo: "lucia.vargas@example.com",
      cargo: "Diseñadora Industrial",
      departamento: "Diseño",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 24,
      nombre: "Pedro Méndez",
      correo: "pedro.mendez@example.com",
      cargo: "Consultor de Estrategia",
      departamento: "Consultoría",
      oficina: "Argentina",
      estadoCuenta: "Activo",
    },
    {
      id: 25,
      nombre: "Rosa Gutiérrez",
      correo: "rosa.gutierrez@example.com",
      cargo: "Especialista en Contenidos",
      departamento: "Marketing",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 26,
      nombre: "Diana López",
      correo: "diana.lopez@example.com",
      cargo: "Coordinadora de Recursos Humanos",
      departamento: "Recursos Humanos",
      oficina: "Perú",
      estadoCuenta: "Activo",
    },
    {
      id: 27,
      nombre: "Héctor Núñez",
      correo: "hector.nunez@example.com",
      cargo: "Desarrollador Móvil",
      departamento: "Tecnología",
      oficina: "Uruguay",
      estadoCuenta: "Activo",
    },
    {
      id: 28,
      nombre: "Emilia Romero",
      correo: "emilia.romero@example.com",
      cargo: "Analista de Calidad",
      departamento: "Calidad",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 29,
      nombre: "Pablo Rojas",
      correo: "pablo.rojas@example.com",
      cargo: "Gerente de Producto",
      departamento: "Producto",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
    {
      id: 30,
      nombre: "Clara Suárez",
      correo: "clara.suarez@example.com",
      cargo: "Analista de Recursos Humanos",
      departamento: "Recursos Humanos",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 31,
      nombre: "Jorge Morales",
      correo: "jorge.morales@example.com",
      cargo: "Ingeniero DevOps",
      departamento: "Infraestructura",
      oficina: "Argentina",
      estadoCuenta: "Activo",
    },
    {
      id: 32,
      nombre: "Camila Navarro",
      correo: "camila.navarro@example.com",
      cargo: "Especialista en Publicidad",
      departamento: "Marketing",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 33,
      nombre: "Sofía Ramírez",
      correo: "sofia.ramirez@example.com",
      cargo: "Desarrolladora Backend",
      departamento: "Tecnología",
      oficina: "Perú",
      estadoCuenta: "Activo",
    },
    {
      id: 34,
      nombre: "Mateo Torres",
      correo: "mateo.torres@example.com",
      cargo: "Analista de Datos",
      departamento: "Inteligencia de Negocios",
      oficina: "Argentina",
      estadoCuenta: "Activo",
    },
    {
      id: 35,
      nombre: "Lucía Fernández",
      correo: "lucia.fernandez@example.com",
      cargo: "Gerente de Ventas",
      departamento: "Comercial",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 36,
      nombre: "Emilio Vargas",
      correo: "emilio.vargas@example.com",
      cargo: "Diseñador Gráfico",
      departamento: "Diseño",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
    {
      id: 37,
      nombre: "Valeria Soto",
      correo: "valeria.soto@example.com",
      cargo: "Especialista en Contenido",
      departamento: "Marketing",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 38,
      nombre: "Andrés Castillo",
      correo: "andres.castillo@example.com",
      cargo: "Administrador de Sistemas",
      departamento: "IT",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 39,
      nombre: "Isabella Herrera",
      correo: "isabella.herrera@example.com",
      cargo: "Asistente de Recursos Humanos",
      departamento: "RRHH",
      oficina: "Perú",
      estadoCuenta: "Activo",
    },
    {
      id: 40,
      nombre: "Diego Morales",
      correo: "diego.morales@example.com",
      cargo: "Especialista en SEO",
      departamento: "Marketing",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 41,
      nombre: "Gabriela López",
      correo: "gabriela.lopez@example.com",
      cargo: "Científica de Datos",
      departamento: "Data Science",
      oficina: "Argentina",
      estadoCuenta: "Activo",
    },
    {
      id: 42,
      nombre: "Sebastián García",
      correo: "sebastian.garcia@example.com",
      cargo: "Especialista en Seguridad",
      departamento: "IT",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 43,
      nombre: "Carolina Méndez",
      correo: "carolina.mendez@example.com",
      cargo: "Analista Financiera",
      departamento: "Finanzas",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 44,
      nombre: "Martín Pérez",
      correo: "martin.perez@example.com",
      cargo: "Jefe de Operaciones",
      departamento: "Operaciones",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
    {
      id: 45,
      nombre: "Fernanda Rojas",
      correo: "fernanda.rojas@example.com",
      cargo: "Consultora de Negocios",
      departamento: "Consultoría",
      oficina: "México",
      estadoCuenta: "Activo",
    },
    {
      id: 46,
      nombre: "Pablo Sánchez",
      correo: "pablo.sanchez@example.com",
      cargo: "Ingeniero de DevOps",
      departamento: "IT",
      oficina: "Argentina",
      estadoCuenta: "Activo",
    },
    {
      id: 47,
      nombre: "Victoria Gómez",
      correo: "victoria.gomez@example.com",
      cargo: "Especialista en Social Media",
      departamento: "Marketing",
      oficina: "Chile",
      estadoCuenta: "Activo",
    },
    {
      id: 48,
      nombre: "Javier Ruiz",
      correo: "javier.ruiz@example.com",
      cargo: "Gerente de Producto",
      departamento: "Innovación",
      oficina: "Perú",
      estadoCuenta: "Activo",
    },
    {
      id: 49,
      nombre: "Paula Medina",
      correo: "paula.medina@example.com",
      cargo: "Editora de Contenido",
      departamento: "Medios",
      oficina: "España",
      estadoCuenta: "Activo",
    },
    {
      id: 50,
      nombre: "Daniel Ortiz",
      correo: "daniel.ortiz@example.com",
      cargo: "Especialista en Publicidad",
      departamento: "Marketing",
      oficina: "Colombia",
      estadoCuenta: "Activo",
    },
  ],
  total: 50,
};
