import { IAuth } from "../store/interfaces/auth.interface";
import { IEmployeeList } from "../store/interfaces/employee.interface";

export const user: IAuth = {
  data: {
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.sampleToken1234567890",
    user: {
      id: 1,
      name: "Demo User",
      email: "demouser@company.com",
      role: "admin",
      department: "Tecnología",
      office: "México",
      accountStatus: "Activo",
    },
  },
  status: "success",
};

export const employees: IEmployeeList = {
  status: "success",
  data: [
    {
      id: 1,
      name: "Carlos Pérez",
      email: "carlos.perez@example.com",
      role: "Desarrollador Frontend",
      department: "Tecnología",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 2,
      name: "Ana Martínez",
      email: "ana.martinez@example.com",
      role: "Analista de Datos",
      department: "Inteligencia de Negocios",
      office: "Colombia",
      accountStatus: "Activo",
    },
    {
      id: 3,
      name: "Luis Gómez",
      email: "luis.gomez@example.com",
      role: "Diseñador UX/UI",
      department: "Diseño",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 4,
      name: "Marta López",
      email: "marta.lopez@example.com",
      role: "Gerente de Proyecto",
      department: "Operaciones",
      office: "Argentina",
      accountStatus: "Activo",
    },
    {
      id: 5,
      name: "Javier Fernández",
      email: "javier.fernandez@example.com",
      role: "Administrador de Sistemas",
      department: "Infraestructura",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 6,
      name: "Sofía Ramírez",
      email: "sofia.ramirez@example.com",
      role: "Especialista en Marketing",
      department: "Marketing",
      office: "Perú",
      accountStatus: "Activo",
    },
    {
      id: 7,
      name: "Diego Torres",
      email: "diego.torres@example.com",
      role: "Científico de Datos",
      department: "Inteligencia de Negocios",
      office: "Uruguay",
      accountStatus: "Activo",
    },
    {
      id: 8,
      name: "Elena Vega",
      email: "elena.vega@example.com",
      role: "Consultor Técnico",
      department: "Tecnología",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 9,
      name: "Mario Sánchez",
      email: "mario.sanchez@example.com",
      role: "Gerente Comercial",
      department: "Ventas",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 10,
      name: "Laura Ortiz",
      email: "laura.ortiz@example.com",
      role: "Asistente Administrativo",
      department: "Administración",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 11,
      name: "Andrés Ruiz",
      email: "andres.ruiz@example.com",
      role: "Especialista en Redes",
      department: "Infraestructura",
      office: "Colombia",
      accountStatus: "Activo",
    },
    {
      id: 12,
      name: "Valeria Castillo",
      email: "valeria.castillo@example.com",
      role: "Analista Financiero",
      department: "Finanzas",
      office: "Perú",
      accountStatus: "Activo",
    },
    {
      id: 13,
      name: "Fernando Gil",
      email: "fernando.gil@example.com",
      role: "Desarrollador Backend",
      department: "Tecnología",
      office: "Uruguay",
      accountStatus: "Activo",
    },
    {
      id: 14,
      name: "Patricia Díaz",
      email: "patricia.diaz@example.com",
      role: "Especialista en SEO",
      department: "Marketing",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 15,
      name: "Hugo Vargas",
      email: "hugo.vargas@example.com",
      role: "Ingeniero de Software",
      department: "Tecnología",
      office: "Colombia",
      accountStatus: "Activo",
    },
    {
      id: 16,
      name: "Gabriela Flores",
      email: "gabriela.flores@example.com",
      role: "Gerente de Recursos Humanos",
      department: "Recursos Humanos",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 17,
      name: "Ricardo Castro",
      email: "ricardo.castro@example.com",
      role: "Desarrollador Fullstack",
      department: "Tecnología",
      office: "Argentina",
      accountStatus: "Activo",
    },
    {
      id: 18,
      name: "Claudia Mendoza",
      email: "claudia.mendoza@example.com",
      role: "Analista de Soporte",
      department: "Infraestructura",
      office: "Perú",
      accountStatus: "Activo",
    },
    {
      id: 19,
      name: "Tomás Herrera",
      email: "tomas.herrera@example.com",
      role: "Administrador de Base de Datos",
      department: "Tecnología",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 20,
      name: "Silvia Romero",
      email: "silvia.romero@example.com",
      role: "Diseñadora Gráfica",
      department: "Diseño",
      office: "Uruguay",
      accountStatus: "Activo",
    },
    {
      id: 21,
      name: "Isabel Peña",
      email: "isabel.pena@example.com",
      role: "Asistente de Ventas",
      department: "Ventas",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 22,
      name: "Oscar León",
      email: "oscar.leon@example.com",
      role: "Analista de Negocios",
      department: "Operaciones",
      office: "Colombia",
      accountStatus: "Activo",
    },
    {
      id: 23,
      name: "Lucía Vargas",
      email: "lucia.vargas@example.com",
      role: "Diseñadora Industrial",
      department: "Diseño",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 24,
      name: "Pedro Méndez",
      email: "pedro.mendez@example.com",
      role: "Consultor de Estrategia",
      department: "Consultoría",
      office: "Argentina",
      accountStatus: "Activo",
    },
    {
      id: 25,
      name: "Rosa Gutiérrez",
      email: "rosa.gutierrez@example.com",
      role: "Especialista en Contenidos",
      department: "Marketing",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 26,
      name: "Diana López",
      email: "diana.lopez@example.com",
      role: "Coordinadora de Recursos Humanos",
      department: "Recursos Humanos",
      office: "Perú",
      accountStatus: "Activo",
    },
    {
      id: 27,
      name: "Héctor Núñez",
      email: "hector.nunez@example.com",
      role: "Desarrollador Móvil",
      department: "Tecnología",
      office: "Uruguay",
      accountStatus: "Activo",
    },
    {
      id: 28,
      name: "Emilia Romero",
      email: "emilia.romero@example.com",
      role: "Analista de Calidad",
      department: "Calidad",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 29,
      name: "Pablo Rojas",
      email: "pablo.rojas@example.com",
      role: "Gerente de Producto",
      department: "Producto",
      office: "Colombia",
      accountStatus: "Activo",
    },
    {
      id: 30,
      name: "Clara Suárez",
      email: "clara.suarez@example.com",
      role: "Analista de Recursos Humanos",
      department: "Recursos Humanos",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 31,
      name: "Jorge Morales",
      email: "jorge.morales@example.com",
      role: "Ingeniero DevOps",
      department: "Infraestructura",
      office: "Argentina",
      accountStatus: "Activo",
    },
    {
      id: 32,
      name: "Camila Navarro",
      email: "camila.navarro@example.com",
      role: "Especialista en Publicidad",
      department: "Marketing",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 33,
      name: "Sofía Ramírez",
      email: "sofia.ramirez@example.com",
      role: "Desarrolladora Backend",
      department: "Tecnología",
      office: "Perú",
      accountStatus: "Activo",
    },
    {
      id: 34,
      name: "Mateo Torres",
      email: "mateo.torres@example.com",
      role: "Analista de Datos",
      department: "Inteligencia de Negocios",
      office: "Argentina",
      accountStatus: "Activo",
    },
    {
      id: 35,
      name: "Lucía Fernández",
      email: "lucia.fernandez@example.com",
      role: "Gerente de Ventas",
      department: "Comercial",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 36,
      name: "Emilio Vargas",
      email: "emilio.vargas@example.com",
      role: "Diseñador Gráfico",
      department: "Diseño",
      office: "Colombia",
      accountStatus: "Activo",
    },
    {
      id: 37,
      name: "Valeria Soto",
      email: "valeria.soto@example.com",
      role: "Especialista en Contenido",
      department: "Marketing",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 38,
      name: "Andrés Castillo",
      email: "andres.castillo@example.com",
      role: "Administrador de Sistemas",
      department: "IT",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 39,
      name: "Isabella Herrera",
      email: "isabella.herrera@example.com",
      role: "Asistente de Recursos Humanos",
      department: "RRHH",
      office: "Perú",
      accountStatus: "Activo",
    },
    {
      id: 40,
      name: "Diego Morales",
      email: "diego.morales@example.com",
      role: "Especialista en SEO",
      department: "Marketing",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 41,
      name: "Gabriela López",
      email: "gabriela.lopez@example.com",
      role: "Científica de Datos",
      department: "Data Science",
      office: "Argentina",
      accountStatus: "Activo",
    },
    {
      id: 42,
      name: "Sebastián García",
      email: "sebastian.garcia@example.com",
      role: "Especialista en Seguridad",
      department: "IT",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 43,
      name: "Carolina Méndez",
      email: "carolina.mendez@example.com",
      role: "Analista Financiera",
      department: "Finanzas",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 44,
      name: "Martín Pérez",
      email: "martin.perez@example.com",
      role: "Jefe de Operaciones",
      department: "Operaciones",
      office: "Colombia",
      accountStatus: "Activo",
    },
    {
      id: 45,
      name: "Fernanda Rojas",
      email: "fernanda.rojas@example.com",
      role: "Consultora de Negocios",
      department: "Consultoría",
      office: "México",
      accountStatus: "Activo",
    },
    {
      id: 46,
      name: "Pablo Sánchez",
      email: "pablo.sanchez@example.com",
      role: "Ingeniero de DevOps",
      department: "IT",
      office: "Argentina",
      accountStatus: "Activo",
    },
    {
      id: 47,
      name: "Victoria Gómez",
      email: "victoria.gomez@example.com",
      role: "Especialista en Social Media",
      department: "Marketing",
      office: "Chile",
      accountStatus: "Activo",
    },
    {
      id: 48,
      name: "Javier Ruiz",
      email: "javier.ruiz@example.com",
      role: "Gerente de Producto",
      department: "Innovación",
      office: "Perú",
      accountStatus: "Activo",
    },
    {
      id: 49,
      name: "Paula Medina",
      email: "paula.medina@example.com",
      role: "Editora de Contenido",
      department: "Medios",
      office: "España",
      accountStatus: "Activo",
    },
    {
      id: 50,
      name: "Daniel Ortiz",
      email: "daniel.ortiz@example.com",
      role: "Especialista en Publicidad",
      department: "Marketing",
      office: "Colombia",
      accountStatus: "Activo",
    },
  ],
  total: 50,
};
